org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.3
minecraft_version_range=[26.3,26.4)
neo_version=26.3.0.6-beta

mod_id=nbtedit
mod_name=NBT Edit
mod_license=MIT
mod_version=1.5.0
mod_group_id=nbtedit

junit_version=5.11.4
